version: '3.8'

services: 
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ".data/mongo:/data"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOTUSER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOTPASS:-password}
